# Generated by Django 2.2rc1 on 2019-03-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('overview', models.TextField()),
                ('poster_img', models.TextField()),
                ('genre_id', models.TextField()),
                ('release_date', models.TextField()),
            ],
        ),
    ]
